# Generated by Django 4.1.7 on 2023-03-10 01:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
