# Generated by Django 4.1.7 on 2023-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_comment_comment_alter_post_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
