# Generated by Django 4.1.7 on 2023-03-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.CharField(blank=True, max_length=133, null=True),
        ),
    ]
