# Generated by Django 4.1.7 on 2023-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_comment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_blank",
            field=models.BooleanField(default=False),
        ),
    ]
