# Generated by Django 4.2 on 2023-09-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_alter_post_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
